#ifndef _CONFIG_H_FROTHFET_REV_D
#define _CONFIG_H_FROTHFET_REV_D

#define YB_HARDWARE_VERSION "FROTHFET_REV_D"
#define YB_MANUFACTURER     "Yarrboard"

#define YB_IS_FROTHFET      1
#define YB_BOARD_NAME       "Frothfet"
#define YB_DEFAULT_HOSTNAME "frothfet"

#define YB_HAS_STATUS_RGB
#define YB_STATUS_RGB_PIN 38

#define YB_HAS_PWM_CHANNELS
#define YB_PWM_CHANNEL_COUNT      8
#define YB_PWM_CHANNEL_PINS       {1, 2, 42, 41, 40, 39, 37, 36}
#define YB_PWM_CHANNEL_FREQUENCY  256
#define YB_PWM_CHANNEL_RESOLUTION 12

#define YB_PWM_CHANNEL_CURRENT_ADC_DRIVER_MCP3564
#define YB_PWM_CHANNEL_CURRENT_ADC_CS   10
#define YB_PWM_CHANNEL_CURRENT_ADC_SCK  11
#define YB_PWM_CHANNEL_CURRENT_ADC_MOSI 12
#define YB_PWM_CHANNEL_CURRENT_ADC_MISO 13
#define YB_PWM_CHANNEL_CURRENT_ADC_IRQ  14
#define YB_PWM_CHANNEL_MAX_AMPS         20.0
#define YB_PWM_CHANNEL_V_PER_AMP        0.132 // ACS725LLCTR-20AU
// #define YB_PWM_CHANNEL_TOTAL_AMPS 100.0

#define YB_HAS_CHANNEL_VOLTAGE
#define YB_PWM_CHANNEL_VOLTAGE_ADC_DRIVER_ADS1115
#define YB_PWM_CHANNEL_VOLTAGE_I2C_ADDRESS_1 0x49
#define YB_PWM_CHANNEL_VOLTAGE_I2C_ADDRESS_2 0x48
#define YB_PWM_CHANNEL_VOLTAGE_R1            4700.0
#define YB_PWM_CHANNEL_VOLTAGE_R2            576.0

#define YB_HAS_BUS_VOLTAGE
#define YB_BUS_VOLTAGE_MCP3425
#define YB_BUS_VOLTAGE_R1      300000.0
#define YB_BUS_VOLTAGE_R2      22000.0
#define YB_BUS_VOLTAGE_ADDRESS 0x68

#define YB_I2C_SDA_PIN 8
#define YB_I2C_SCL_PIN 9

#define YB_HAS_FANS
#define YB_FAN_COUNT                     2
#define YB_FAN_MOSFET_PINS               {15, 5}
#define YB_FAN_TACH_PINS                 {17, 7}
#define YB_FAN_SINGLE_CHANNEL_THRESHOLD  10
#define YB_FAN_AVERAGE_CHANNEL_THRESHOLD 5

#endif // _CONFIG_FROTHFET_REV_D