#ifndef _CONFIG_H_FROTHFET_REV_E
#define _CONFIG_H_FROTHFET_REV_E

#define YB_HARDWARE_VERSION "FROTHFET_REV_E"
#define YB_MANUFACTURER     "Yarrboard"

#define YB_IS_FROTHFET      1
#define YB_BOARD_NAME       "Frothfet"
#define YB_DEFAULT_HOSTNAME "frothfet"

#define YB_HAS_STATUS_RGB
#define YB_STATUS_RGB_PIN   38
#define YB_STATUS_RGB_COUNT 9

#define YB_HAS_PIEZO
#define YB_PIEZO_ACTIVE
#define YB_PIEZO_PIN 21

#define YB_HAS_PWM_CHANNELS
#define YB_PWM_CHANNEL_COUNT 8
#define YB_PWM_CHANNEL_PINS  {9, 8, 7, 6, 5, 4, 2, 1}
#define YB_PWM_CHANNEL_INVERTED
#define YB_PWM_CHANNEL_FREQUENCY  1000
#define YB_PWM_CHANNEL_RESOLUTION 12

#define YB_PWM_CHANNEL_CURRENT_ADC_DRIVER_MCP3564
#define YB_PWM_CHANNEL_CURRENT_ADC_CS   18
#define YB_PWM_CHANNEL_CURRENT_ADC_SCK  39
#define YB_PWM_CHANNEL_CURRENT_ADC_MOSI 40
#define YB_PWM_CHANNEL_CURRENT_ADC_MISO 41
#define YB_PWM_CHANNEL_CURRENT_ADC_IRQ  17
#define YB_PWM_CHANNEL_MAX_AMPS         20.0
#define YB_PWM_CHANNEL_V_PER_AMP        0.100 // TMCS1108A2U
// #define YB_PWM_CHANNEL_TOTAL_AMPS 100.0

#define YB_HAS_CHANNEL_VOLTAGE
#define YB_PWM_CHANNEL_VOLTAGE_ADC_DRIVER_MCP3564
#define YB_PWM_CHANNEL_VOLTAGE_ADC_CS   42
#define YB_PWM_CHANNEL_VOLTAGE_ADC_SCK  39
#define YB_PWM_CHANNEL_VOLTAGE_ADC_MOSI 40
#define YB_PWM_CHANNEL_VOLTAGE_ADC_MISO 41
#define YB_PWM_CHANNEL_VOLTAGE_ADC_IRQ  14
#define YB_PWM_CHANNEL_VOLTAGE_R1       27000.0
#define YB_PWM_CHANNEL_VOLTAGE_R2       3300.0

#define YB_HAS_BUS_VOLTAGE
#define YB_BUS_VOLTAGE_MCP3425
#define YB_BUS_VOLTAGE_R1      300000.0
#define YB_BUS_VOLTAGE_R2      22000.0
#define YB_BUS_VOLTAGE_ADDRESS 0x68

#define YB_I2C_SDA_PIN 47
#define YB_I2C_SCL_PIN 48

#define YB_HAS_FANS
#define YB_FAN_COUNT                     2
#define YB_FAN_MOSFET_PINS               {12, 10}
#define YB_FAN_TACH_PINS                 {13, 11}
#define YB_FAN_SINGLE_CHANNEL_THRESHOLD  10
#define YB_FAN_AVERAGE_CHANNEL_THRESHOLD 5

#endif // _CONFIG_FROTHFET_REV_E