#ifndef _CONFIG_H_FROTHFET_REV_F
#define _CONFIG_H_FROTHFET_REV_F

#define YB_HARDWARE_VERSION "FROTHFET_REV_F"
#define YB_MANUFACTURER     "Yarrboard"

#define YB_IS_FROTHFET      1
#define YB_BOARD_NAME       "Frothfet"
#define YB_DEFAULT_HOSTNAME "frothfet"

#define YB_HAS_STATUS_RGB
#define YB_STATUS_RGB_PIN   38
#define YB_STATUS_RGB_COUNT 9

#define YB_HAS_PIEZO
#define YB_PIEZO_ACTIVE
#define YB_PIEZO_PIN 14

#define YB_HAS_PWM_CHANNELS
#define YB_PWM_CHANNEL_COUNT           8
#define YB_PWM_CHANNEL_PINS            {9, 8, 7, 6, 5, 4, 2, 1}
#define YB_PWM_CHANNEL_ENABLE_PIN      21
#define YB_PWM_CHANNEL_INVERTED        true
#define YB_PWM_CHANNEL_FREQUENCY       1000
#define YB_PWM_CHANNEL_RESOLUTION      12
#define YB_PWM_CHANNEL_MAX_AMPS        20.0
#define YB_PWM_CHANNEL_MAX_TEMPERATURE 80.0

#define YB_PWM_CHANNEL_HAS_INA226
#define YB_PWM_CHANNEL_INA226_SHUNT   0.002
#define YB_PWM_CHANNEL_INA226_ADDRESS {0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47}
#define YB_PWM_CHANNEL_INA226_ALERT   {15, 16, 17, 18, 42, 41, 40, 39}

#define YB_PWM_CHANNEL_HAS_LM75
#define YB_PWM_CHANNEL_LM75_ADDRESS {0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D, 0x4E, 0x4F};

#define YB_HAS_BUS_VOLTAGE
#define YB_BUS_VOLTAGE_MCP3425
#define YB_BUS_VOLTAGE_R1      300000.0
#define YB_BUS_VOLTAGE_R2      22000.0
#define YB_BUS_VOLTAGE_ADDRESS 0x68

#define YB_I2C_SDA_PIN 48
#define YB_I2C_SCL_PIN 47

#define YB_HAS_FANS
#define YB_FAN_COUNT                     2
#define YB_FAN_MOSFET_PINS               {12, 10}
#define YB_FAN_TACH_PINS                 {13, 11}
#define YB_FAN_SINGLE_CHANNEL_THRESHOLD  10
#define YB_FAN_AVERAGE_CHANNEL_THRESHOLD 5

#endif // _CONFIG_FROTHFET_REV_E