#ifndef BRINEOMATIC_CONFIG_H
#define BRINEOMATIC_CONFIG_H

#ifndef YB_TANK_LEVEL_FULL
  #define YB_TANK_LEVEL_FULL 0.99
#endif

#ifndef YB_TANK_CAPACITY
  #define YB_TANK_CAPACITY 780
#endif

#ifndef YB_COOLING_FAN_ON_TEMPERATURE
  #define YB_COOLING_FAN_ON_TEMPERATURE 35.0
#endif

#ifndef YB_COOLING_FAN_OFF_TEMPERATURE
  #define YB_COOLING_FAN_OFF_TEMPERATURE 34.0
#endif

#ifndef YB_AUTOFLUSH_MODE
  #define YB_AUTOFLUSH_MODE "TIME"
#endif

#ifndef YB_AUTOFLUSH_SALINITY
  #define YB_AUTOFLUSH_SALINITY 750.0
#endif

#ifndef YB_AUTOFLUSH_DURATION
  #define YB_AUTOFLUSH_DURATION (3 * 60 * 1000)
#endif

#ifndef YB_AUTOFLUSH_VOLUME
  #define YB_AUTOFLUSH_VOLUME 15.0
#endif

#ifndef YB_AUTOFLUSH_INTERVAL
  #define YB_AUTOFLUSH_INTERVAL (3 * 24 * 60 * 60 * 1000)
#endif

#ifndef YB_AUTOFLUSH_USE_HIGH_PRESSURE_MOTOR
  #define YB_AUTOFLUSH_USE_HIGH_PRESSURE_MOTOR false
#endif

#ifndef YB_TEMPERATURE_UNITS
  #define YB_TEMPERATURE_UNITS "celsius"
#endif

#ifndef YB_PRESSURE_UNITS
  #define YB_PRESSURE_UNITS "psi"
#endif

#ifndef YB_VOLUME_UNITS
  #define YB_VOLUME_UNITS "liters"
#endif

#ifndef YB_FLOWRATE_UNITS
  #define YB_FLOWRATE_UNITS "lph"
#endif

#ifndef YB_SUCCESS_MELODY
  #define YB_SUCCESS_MELODY "SUCCESS"
#endif

#ifndef YB_ERROR_MELODY
  #define YB_ERROR_MELODY "ERROR"
#endif

#ifndef YB_BOOST_PUMP_CONTROL
  #define YB_BOOST_PUMP_CONTROL "NONE"
#endif

#ifndef YB_BOOST_PUMP_RELAY_ID
  #define YB_BOOST_PUMP_RELAY_ID 1
#endif

#ifndef YB_HIGH_PRESSURE_PUMP_CONTROL
  #define YB_HIGH_PRESSURE_PUMP_CONTROL "RELAY"
#endif

#ifndef YB_HIGH_PRESSURE_RELAY_ID
  #define YB_HIGH_PRESSURE_RELAY_ID 2
#endif

#ifndef YB_HIGH_PRESSURE_PUMP_MODBUS_DEVICE
  #define YB_HIGH_PRESSURE_PUMP_MODBUS_DEVICE "GD20"
#endif

#ifndef YB_HIGH_PRESSURE_PUMP_MODBUS_SLAVE_ID
  #define YB_HIGH_PRESSURE_PUMP_MODBUS_SLAVE_ID 0
#endif

#ifndef YB_HIGH_PRESSURE_PUMP_MODBUS_FREQUENCY
  #define YB_HIGH_PRESSURE_PUMP_MODBUS_FREQUENCY 25.0
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_CONTROL
  #define YB_HIGH_PRESSURE_VALVE_CONTROL "MANUAL"
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_STEPPER_ID
  #define YB_HIGH_PRESSURE_VALVE_STEPPER_ID 1
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_STEPPER_STEP_ANGLE
  #define YB_HIGH_PRESSURE_VALVE_STEPPER_STEP_ANGLE 1.8
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_STEPPER_GEAR_RATIO
  #define YB_HIGH_PRESSURE_VALVE_STEPPER_GEAR_RATIO 3.0
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_STEPPER_CLOSE_ANGLE
  #define YB_HIGH_PRESSURE_VALVE_STEPPER_CLOSE_ANGLE 1660.0
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_STEPPER_CLOSE_SPEED
  #define YB_HIGH_PRESSURE_VALVE_STEPPER_CLOSE_SPEED 10.0
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_STEPPER_OPEN_ANGLE
  #define YB_HIGH_PRESSURE_VALVE_STEPPER_OPEN_ANGLE 0.0
#endif

#ifndef YB_HIGH_PRESSURE_VALVE_STEPPER_OPEN_SPEED
  #define YB_HIGH_PRESSURE_VALVE_STEPPER_OPEN_SPEED 40.0
#endif

#ifndef YB_MEMBRANE_PRESSURE_TARGET
  #define YB_MEMBRANE_PRESSURE_TARGET 800.0
#endif

#ifndef YB_DIVERTER_VALVE_CONTROL
  #define YB_DIVERTER_VALVE_CONTROL "SERVO"
#endif

#ifndef YB_DIVERTER_VALVE_RELAY_ID
  #define YB_DIVERTER_VALVE_RELAY_ID 0
#endif

#ifndef YB_DIVERTER_VALVE_RELAY_INVERTED
  #define YB_DIVERTER_VALVE_RELAY_INVERTED false
#endif

#ifndef YB_DIVERTER_VALVE_SERVO_ID
  #define YB_DIVERTER_VALVE_SERVO_ID 1
#endif

#ifndef YB_DIVERTER_VALVE_OPEN_ANGLE
  #define YB_DIVERTER_VALVE_OPEN_ANGLE 35
#endif

#ifndef YB_DIVERTER_VALVE_CLOSE_ANGLE
  #define YB_DIVERTER_VALVE_CLOSE_ANGLE 125
#endif

#ifndef YB_FLUSH_VALVE_CONTROL
  #define YB_FLUSH_VALVE_CONTROL "RELAY"
#endif

#ifndef YB_FLUSH_VALVE_RELAY_ID
  #define YB_FLUSH_VALVE_RELAY_ID 3
#endif

#ifndef YB_COOLING_FAN_CONTROL
  #define YB_COOLING_FAN_CONTROL "RELAY"
#endif

#ifndef YB_COOLING_FAN_RELAY_ID
  #define YB_COOLING_FAN_RELAY_ID 4
#endif

#ifndef YB_HAS_MEMBRANE_PRESSURE_SENSOR
  #define YB_HAS_MEMBRANE_PRESSURE_SENSOR true
#endif

#ifndef YB_MEMBRANE_PRESSURE_SENSOR_MIN
  #define YB_MEMBRANE_PRESSURE_SENSOR_MIN 0.0
#endif

#ifndef YB_MEMBRANE_PRESSURE_SENSOR_MAX
  #define YB_MEMBRANE_PRESSURE_SENSOR_MAX 1000.0
#endif

#ifndef YB_HAS_FILTER_PRESSURE_SENSOR
  #define YB_HAS_FILTER_PRESSURE_SENSOR true
#endif

#ifndef YB_FILTER_PRESSURE_SENSOR_MIN
  #define YB_FILTER_PRESSURE_SENSOR_MIN 0.0
#endif

#ifndef YB_FILTER_PRESSURE_SENSOR_MAX
  #define YB_FILTER_PRESSURE_SENSOR_MAX 50.0
#endif

#ifndef YB_HAS_PRODUCT_TDS_SENSOR
  #define YB_HAS_PRODUCT_TDS_SENSOR true
#endif

#ifndef YB_HAS_BRINE_TDS_SENSOR
  #define YB_HAS_BRINE_TDS_SENSOR true
#endif

#ifndef YB_HAS_PRODUCT_FLOW_SENSOR
  #define YB_HAS_PRODUCT_FLOW_SENSOR true
#endif

#ifndef YB_PRODUCT_FLOWMETER_PPL
  #define YB_PRODUCT_FLOWMETER_PPL 1260.0
#endif

#ifndef YB_HAS_BRINE_FLOW_SENSOR
  #define YB_HAS_BRINE_FLOW_SENSOR true
#endif

#ifndef YB_BRINE_FLOWMETER_PPL
  #define YB_BRINE_FLOWMETER_PPL 1260.0
#endif

#ifndef YB_HAS_MOTOR_TEMPERATURE_SENSOR
  #define YB_HAS_MOTOR_TEMPERATURE_SENSOR true
#endif

#ifndef YB_ENABLE_MEMBRANE_PRESSURE_HIGH_CHECK
  #define YB_ENABLE_MEMBRANE_PRESSURE_HIGH_CHECK true
#endif

#ifndef YB_MEMBRANE_PRESSURE_HIGH_THRESHOLD
  #define YB_MEMBRANE_PRESSURE_HIGH_THRESHOLD 900.0
#endif

#ifndef YB_MEMBRANE_PRESSURE_HIGH_DELAY
  #define YB_MEMBRANE_PRESSURE_HIGH_DELAY 2000
#endif

#ifndef YB_ENABLE_MEMBRANE_PRESSURE_LOW_CHECK
  #define YB_ENABLE_MEMBRANE_PRESSURE_LOW_CHECK true
#endif

#ifndef YB_MEMBRANE_PRESSURE_LOW_THRESHOLD
  #define YB_MEMBRANE_PRESSURE_LOW_THRESHOLD 700.0
#endif

#ifndef YB_MEMBRANE_PRESSURE_LOW_DELAY
  #define YB_MEMBRANE_PRESSURE_LOW_DELAY 2000
#endif

#ifndef YB_ENABLE_FILTER_PRESSURE_HIGH_CHECK
  #define YB_ENABLE_FILTER_PRESSURE_HIGH_CHECK true
#endif

#ifndef YB_FILTER_PRESSURE_HIGH_THRESHOLD
  #define YB_FILTER_PRESSURE_HIGH_THRESHOLD 60.0
#endif

#ifndef YB_FILTER_PRESSURE_HIGH_DELAY
  #define YB_FILTER_PRESSURE_HIGH_DELAY 2000
#endif

#ifndef YB_ENABLE_FILTER_PRESSURE_LOW_CHECK
  #define YB_ENABLE_FILTER_PRESSURE_LOW_CHECK true
#endif

#ifndef YB_FILTER_PRESSURE_LOW_THRESHOLD
  #define YB_FILTER_PRESSURE_LOW_THRESHOLD 2.5
#endif

#ifndef YB_FILTER_PRESSURE_LOW_DELAY
  #define YB_FILTER_PRESSURE_LOW_DELAY 2000
#endif

#ifndef YB_ENABLE_PRODUCT_FLOWRATE_HIGH_CHECK
  #define YB_ENABLE_PRODUCT_FLOWRATE_HIGH_CHECK true
#endif

#ifndef YB_PRODUCT_FLOWRATE_HIGH_THRESHOLD
  #define YB_PRODUCT_FLOWRATE_HIGH_THRESHOLD 165.0
#endif

#ifndef YB_PRODUCT_FLOWRATE_HIGH_DELAY
  #define YB_PRODUCT_FLOWRATE_HIGH_DELAY (10 * 1000)
#endif

#ifndef YB_ENABLE_PRODUCT_FLOWRATE_LOW_CHECK
  #define YB_ENABLE_PRODUCT_FLOWRATE_LOW_CHECK true
#endif

#ifndef YB_PRODUCT_FLOWRATE_LOW_THRESHOLD
  #define YB_PRODUCT_FLOWRATE_LOW_THRESHOLD 120.0
#endif

#ifndef YB_PRODUCT_FLOWRATE_LOW_DELAY
  #define YB_PRODUCT_FLOWRATE_LOW_DELAY (10 * 1000)
#endif

#ifndef YB_ENABLE_RUN_TOTAL_FLOWRATE_LOW_CHECK
  #define YB_ENABLE_RUN_TOTAL_FLOWRATE_LOW_CHECK true
#endif

#ifndef YB_RUN_TOTAL_FLOWRATE_LOW_THRESHOLD
  #define YB_RUN_TOTAL_FLOWRATE_LOW_THRESHOLD 300.0
#endif

#ifndef YB_RUN_TOTAL_FLOWRATE_LOW_DELAY
  #define YB_RUN_TOTAL_FLOWRATE_LOW_DELAY 2500
#endif

#ifndef YB_ENABLE_PICKLE_TOTAL_FLOWRATE_LOW_CHECK
  #define YB_ENABLE_PICKLE_TOTAL_FLOWRATE_LOW_CHECK true
#endif

#ifndef YB_PICKLE_TOTAL_FLOWRATE_LOW_THRESHOLD
  #define YB_PICKLE_TOTAL_FLOWRATE_LOW_THRESHOLD 300.0
#endif

#ifndef YB_PICKLE_TOTAL_FLOWRATE_LOW_DELAY
  #define YB_PICKLE_TOTAL_FLOWRATE_LOW_DELAY 2500
#endif

#ifndef YB_ENABLE_DIVERTER_VALVE_CLOSED_CHECK
  #define YB_ENABLE_DIVERTER_VALVE_CLOSED_CHECK true
#endif

#ifndef YB_DIVERTER_VALVE_CLOSED_DELAY
  #define YB_DIVERTER_VALVE_CLOSED_DELAY 5000
#endif

#ifndef YB_ENABLE_PRODUCT_SALINITY_HIGH_CHECK
  #define YB_ENABLE_PRODUCT_SALINITY_HIGH_CHECK true
#endif

#ifndef YB_PRODUCT_SALINITY_HIGH_THRESHOLD
  #define YB_PRODUCT_SALINITY_HIGH_THRESHOLD 500.0
#endif

#ifndef YB_PRODUCT_SALINITY_HIGH_DELAY
  #define YB_PRODUCT_SALINITY_HIGH_DELAY 1000
#endif

#ifndef YB_ENABLE_MOTOR_TEMPERATURE_CHECK
  #define YB_ENABLE_MOTOR_TEMPERATURE_CHECK true
#endif

#ifndef YB_MOTOR_TEMPERATURE_HIGH_THRESHOLD
  #define YB_MOTOR_TEMPERATURE_HIGH_THRESHOLD 65.0
#endif

#ifndef YB_MOTOR_TEMPERATURE_HIGH_DELAY
  #define YB_MOTOR_TEMPERATURE_HIGH_DELAY 1000
#endif

#ifndef YB_ENABLE_FLUSH_FLOWRATE_LOW_CHECK
  #define YB_ENABLE_FLUSH_FLOWRATE_LOW_CHECK true
#endif

#ifndef YB_FLUSH_FLOWRATE_LOW_THRESHOLD
  #define YB_FLUSH_FLOWRATE_LOW_THRESHOLD 100.0
#endif

#ifndef YB_FLUSH_FLOWRATE_LOW_DELAY
  #define YB_FLUSH_FLOWRATE_LOW_DELAY 2500
#endif

#ifndef YB_ENABLE_FLUSH_FILTER_PRESSURE_LOW_CHECK
  #define YB_ENABLE_FLUSH_FILTER_PRESSURE_LOW_CHECK true
#endif

#ifndef YB_FLUSH_FILTER_PRESSURE_LOW_THRESHOLD
  #define YB_FLUSH_FILTER_PRESSURE_LOW_THRESHOLD 15.0
#endif

#ifndef YB_FLUSH_FILTER_PRESSURE_LOW_DELAY
  #define YB_FLUSH_FILTER_PRESSURE_LOW_DELAY 2500
#endif

#ifndef YB_ENABLE_FLUSH_VALVE_OFF_CHECK
  #define YB_ENABLE_FLUSH_VALVE_OFF_CHECK true
#endif

#ifndef YB_FLUSH_VALVE_OFF_THRESHOLD
  #define YB_FLUSH_VALVE_OFF_THRESHOLD 2.0
#endif

#ifndef YB_FLUSH_VALVE_OFF_DELAY
  #define YB_FLUSH_VALVE_OFF_DELAY (15 * 1000)
#endif

#ifndef YB_FLUSH_TIMEOUT
  #define YB_FLUSH_TIMEOUT (5 * 60 * 1000)
#endif

#ifndef YB_MEMBRANE_PRESSURE_TIMEOUT
  #define YB_MEMBRANE_PRESSURE_TIMEOUT (60 * 1000)
#endif

#ifndef YB_PRODUCT_FLOWRATE_TIMEOUT
  #define YB_PRODUCT_FLOWRATE_TIMEOUT (2 * 60 * 1000)
#endif

#ifndef YB_PRODUCT_SALINITY_TIMEOUT
  #define YB_PRODUCT_SALINITY_TIMEOUT (5 * 60 * 1000)
#endif

#ifndef YB_PRODUCTION_RUNTIME_TIMEOUT
  #define YB_PRODUCTION_RUNTIME_TIMEOUT (12 * 60 * 60 * 1000)
#endif

#endif // BRINEOMATIC_CONFIG_H